apiVersion: v1
kind: Service
metadata:
  name: my-webapp-service
spec:
  selector:
    app: my-webapp
  ports:
    - protocol: TCP
      port: 80       # Port inside the cluster
      targetPort: 80 # Port on the pod
      # Port on the EC2 instance (Node). Range: 30000-32767
      nodePort: 30080
  type: NodePort # Exposes the service on each Node's IP at a static port
