name: Deploy to Minikube on AWS

# on:
#   push:
#     branches:
#       - main

jobs:
  build-and-push-docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-devops-app:latest

  deploy-to-aws:
    name: Provision and Deploy to AWS
    runs-on: ubuntu-latest
    needs: build-and-push-docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform

      - name: Get instance IP
        id: get_ip
        run: echo "INSTANCE_IP=$(terraform output -raw instance_public_ip)" >> $GITHUB_ENV
        working-directory: ./terraform

      - name: Wait for SSH to be ready
        run: |
          echo "Waiting for 2 minutes for the EC2 instance to be ready for SSH..."
          sleep 120
      
      - name: Prepare K8s manifests
        run: |
          sed -i 's|yourdockerhubusername|${{ secrets.DOCKERHUB_USERNAME }}|g' k8s/deployment.yaml
          echo "DEPLOYMENT_YAML=$(cat k8s/deployment.yaml | base64 -w 0)" >> $GITHUB_ENV
          echo "SERVICE_YAML=$(cat k8s/service.yaml | base64 -w 0)" >> $GITHUB_ENV

      - name: Deploy to Minikube
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.INSTANCE_IP }}
          username: ubuntu
          key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
          script: |
            echo "Connected to instance. Waiting for Minikube to stabilize..."
            sleep 60
            echo "Applying Kubernetes manifests..."
            echo "${{ env.SERVICE_YAML }}" | base64 -d | sudo -u ubuntu kubectl apply -f -
            echo "${{ env.DEPLOYMENT_YAML }}" | base64 -d | sudo -u ubuntu kubectl apply -f -
            echo "Deployment successful!"

      - name: Debug Server State
        if: always() # This step will run even if the previous steps fail
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.INSTANCE_IP }}
          username: ubuntu
          key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
          script: |
            echo "--- DEBUGGING SERVER STATE ---"
            echo "--- Docker Status ---"
            docker ps -a
            echo "--- Minikube Status ---"
            sudo -u ubuntu minikube status
            echo "--- Kubernetes Resources ---"
            sudo -u ubuntu kubectl get all --all-namespaces
            echo "--- Network Listeners ---"
            sudo netstat -tulpn | grep LISTEN
            echo "--- Testing NodePort Locally ---"
            curl -v http://localhost:30080
            echo "--- End of Debugging ---"
